version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: kirirut
      POSTGRES_PASSWORD: 2811
      POSTGRES_DB: CRM
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
