name: CI - Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: CI

    env:
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build package
        run: mvn clean package

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U $POSTGRES_USER && echo "Postgres is ready" && exit 0
            echo "Waiting for Postgres..."
            sleep 5
          done
          echo "Postgres is not responding" && exit 1
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Build project
        run: SPRING_PROFILES_ACTIVE=ci mvn clean install -B

      - name: Run tests
        run: mvn test -B

      - name: Stop Docker Compose
        run: docker compose down
